sudo: require
language: cpp
compiler: gcc
before_install:
    - gcc --version
    - g++ --version
    - sudo rm -rf /var/lib/apt/lists/partial/*
    - sudo apt-get install -y cmake
    - sudo apt-get install -y libgtest-dev
    - sudo apt-get install -y python2.7 python-pip
    - sudo python2.7 -m pip install pytest scipy
    - sudo apt-get install swig3.0
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ls -l
    - cd ..
    - sudo python2.7 setup.py install
script:
    - ./build/tests/jamspell_tests
    - python2.7 -m pytest -v test_jamspell.py
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
